### PR TITLE
Update Quest [Id]

### PR DESCRIPTION
**Pull request by vrarara**

### CODE REVIEW

**Comment by hufuhufu** [comment]
@dragonjet i just realize this but @vrarara hasn't been added to the translator team
I guess that's why he keep making pull request xD

**Comment by Crazyteitoku** [comment]
@hufuhufu invitation has been sent but I don't think @vrarara has accepted. Please refer to the following screenshot:

**Comment by vrarara** [comment]
uh sorry n thanks @Crazyteitoku  i dont realize if i got an invitation, and once again, sorry

**Comment by Crazyteitoku** [comment]
@vrarara no problem :sweat_smile: though I think it was @dragonjet whom sent out the invitation to you. Don't sweat over it. :smile:

**Pull request merged**
