### PR TITLE
[DE] Changes to Names/Terms in the Quest File

### PR DESCRIPTION
**Pull request by RandomGuyB5**
*Changes to Names/Terms for consistency with @Admiral-Mikado Translations

*I am very sorry for any mistakes or miss translations

### CODE REVIEW

**Comment by RandomGuyB5** [comment]
Oh, okay sorry, so for example:

This:
    "101": {
        "code": "A1",
        "name": "EXAMPLE!",
        "desc": "EXAMPLE DESC.",
        "memo": "\u27a3EXAMPLE'",
        "unlock": [ 102 ]

Could or Should be just this:

    "101": {
        "code": "A1",
        "name": "EXAMPLE!",
        "desc": "EXAMPLE DESC.",
        "memo": "\u27a3EXAMPLE'",

Is this Correct?

**Comment by sinsinpub** [comment]
@RandomGuyB5 yes, that's right.
and the `code` can be omitted too if the German community people also follow [the same ID system](http://kancolle.wikia.com/wiki/Quests).
btw, the `trackingDesc` is different from `tracking`, should be kept and translated.

**Comment by RandomGuyB5** [comment]
Let's just pretend i didn't need six tries to find all the unneeded commas okay?

**Comment by sinsinpub** [comment]
haha, tbh if u r not using a text editor supporting JSON validation, u might try an online JSON validator, like:
https://jsonlint.com/
https://codebeautify.org/jsonvalidator

**Pull request merged**
