### PR TITLE
At least i`ve done it.

### PR DESCRIPTION
**Pull request by JoyceTheBleak**
Its basic version of Ukrainian translation. Its little old, but henceforth i`ll work with it

### CODE REVIEW

**Comment by dragonjet** [comment]
thanks :+1:
I'll merge this, pull from main repo and add it on settings.
I'll also add you to translators list, wherein you can tell me up to 5 links to add under your name

**Comment by dragonjet** [comment]
also, seems the build failed.

travis points at:
```
>> File "build/ua/quests.json" failed JSON validation at line 1248.
Warning: Parse error on line 1249:
...скадрильї Томонаґи "Тензанами"!",      
-----------------------^
```

**Comment by JoyceTheBleak** [comment]
Oh, i`ll watch, whats wrong, right now

**Comment by JoyceTheBleak** [comment]
Hmm, i have no idea what to do

**Comment by dragonjet** [comment]
wait

**Comment by dragonjet** [comment]
```
"desc": "Включи до флоту флагман, оснащений винищувачами Зеро Тип 52 С (601-ша авіабригада), після чого утилізуй 2 \"Реппу\""
```

you'll need two quotation marks at the end `""` because one is for the "penny" and the other for the original `desc` enclosure

**Comment by JoyceTheBleak** [comment]
Yep!

**Comment by dragonjet** [comment]
perfect :+1: 
let me know if you're ready so I'll merge

**Comment by JoyceTheBleak** [comment]
Em, Im ready, or i have to do something else?

**Comment by dragonjet** [comment]
ah it's alright. just give me up to 5 links we can add under your name in the credits page

**Comment by JoyceTheBleak** [comment]
Hmm, what a links? My contacts?

**Comment by dragonjet** [comment]
any link actually - depends on people. some prefer not to share private profiles, but some prefer sharing their website, fan pages or twitter so people can follow

also, we put the native language name in the settings page, e.g. "Français" instead of "French" and "Deutsch" instead of "German". How do you call "Ukrainian" in native language?

**Comment by JoyceTheBleak** [comment]
"Українська" 
I have a Facebook profile and profile in vk.com
https://www.facebook.com/rostyslav.fed
https://vk.com/joyce_the_bleak

**Comment by dragonjet** [comment]
this looks alright so far?

chrome_2016-11-20_15-15-33

**Comment by JoyceTheBleak** [comment]
Yes, its good, some spaces and all will be fine :)

**Comment by sinsinpub** [comment]
some files are not in UTF-8 charset.
may I do converting and some cleaning?

**Comment by JoyceTheBleak** [comment]
yes, of course, thanks

**Comment by sinsinpub** [comment]
ps. are u using KOI8-U charset?

**Comment by JoyceTheBleak** [comment]
Sorry, but I`m completely out of understanding you (what is KOI8-U?)

**Comment by JoyceTheBleak** [comment]
So, thank you all, I`ll go sleep (9:34 in GMT+2, sleepless night)

**Comment by sinsinpub** [comment]
oh... I don't know about Ukrainian. so I'm not sure if I convert your unknown local charset(possible options are Cyrillic Windows/‎KOI8-R/KOI8-U/‎KOI8-RU/‎KOI8-F) to UTF-8, there must be wrong result.

it's better for u to do the convert. For example, edit with Windows notepad, just select the UTF-8 encoding charset from combo menu at Save As dialogue.

Files not in UTF-8 are: `battle.json`, `ranks.json`, `servers.json`. Others are okay.

**Comment by JoyceTheBleak** [comment]
Ok, I`ve changed charset to UTF-8. Is new pull rquest required?

**Pull request merged**
