### PR TITLE
Translation (de)

### PR DESCRIPTION
**Pull request by DesDiv6**
Hello dev team,
the changes worked quite fine for me when I tested them.
The only thing of note I stumbled across was that in "battle" "aacitype" the "ä,ö,ü" are not showing when in Strategy Room -> Library -> Ships. Instead they are replaced by a "?". Maybe someone else has an idea how to fix that. If not, feel free to scratch that part.
Other than that it's only a normal translation with some minor corrections of spelling mistakes here and there. I might have made just as many. Haha.

Anyway, thanks for working so hard. Please keep up the good work.

Best regards
A silent supporter

### CODE REVIEW

**Comment by nonsensed** [comment]
You can probably see if unicode will do the job. Personally I end up using codes a lot for different characters.
ä = \u00e4
ö = \u00f6
ü = \u00fc

example:
`"SettingsQuestOverlay" : "Quest\u00fcbersetzungen",`

**Comment by sinsinpub** [comment]
saving these json files as text with UTF-8 also works

**Comment by dragonjet** [comment]
in case you don't have an editor that does what @sinsinpub mentioned, you can use this online tool

https://www.functions-online.com/json_encode.html

chrome_2017-01-24_10-09-03

**Comment by DesDiv6** [comment]
Thanks for the help and suggestions. The game shows the letters just fine after using unicode.
And sorry for adding "terms" multiple times. I thought only the last update would show up here.

**Comment by sinsinpub** [comment]
I cannot read Deutsch to review contents of translation itself, but i feel i can help to fix the file unicode issue.
let me merge it first. if any translation issue found, just open another PR.

**Comment by sinsinpub** [comment]
something found in terms:
 * some `KC3改` is broken, I fixed it
 * some words need to be shorten to fix the limited display space. for example: `Auf Standard zurücksetzen` (Reset to default) is too long. how about just `Zurücksetzen`?

**Comment by DesDiv6** [comment]
Yeah, that's fine.
Do you have a way to test that aside from starting the game and trying it out? Because that's how I worked in order to figure out how long words or sentences can be in order to fit the screen-length.
Also thank you for your help. It's much appreciated.

**Comment by sinsinpub** [comment]
unfortunately, for the terms used in devtools panel, try them out in game is the only way I know for now...
If u r familiar with using Chrome devtools, there is a proper way:
undock the devtools of KC3 to separated window, then push Shift+Ctrl+I to open yet another devtools of the KC3 panel. In the  elements tab, you can select element by mouse pointer, see the layout, modify text of element to see how it displayed immediately.

**Pull request merged**
