### PR TITLE
[JP] Whiteday 2018

### PR DESCRIPTION
**Pull request by redpizza**
but this year's whiteday is gone:sob:

### CODE REVIEW

**Comment by redpizza** [comment]
Huh? I'm not understanding well what `Anti-Bomber MVPs` meaning...
but, I think current `BattleHistoryAirRaidTip`'s text is not correctly as Japanese.
I suggest `迎撃MVP中隊` instead of `迎撃に対敵爆撃最も有効の中隊`.

**Comment by redpizza** [comment]
🤔
Recent `BattleHistoryAirRaidTip` changes (d3d32bf) was not proper?
So, this tip shows just "highest anti-bomber stat squadrons in all bases set to defense". I understood.
then text shoud be say so, not "MVP" or "effective"...
translate that, I suggest `各防空部隊で耐爆値が最も高い中隊` in JP.

**Comment by sinsinpub** [comment]
yep, that sounds better. (there a typo: `耐`)
btw, to learn why top anti-bomber stat planes are shown, could see verification article like this:
http://nishisonic.xsrv.jp/archives/504 (防空時の局戦・陸戦まとめ)

**Comment by redpizza** [comment]
Kancolle game mechanics is too difficult for me🤔
I stopped thinking about LBAS system😇

**Pull request merged**
