### PR TITLE
added text for new setting

### PR DESCRIPTION
**Pull request by DynamicSTOP**
see https://github.com/KC3Kai/KC3Kai/pull/1441

Might not be the best choice in case of sense, but better then nothing :)

### CODE REVIEW

**Comment by dragonjet** [comment]
ah we still need this right? :sweat_smile:

**Comment by DynamicSTOP** [comment]
yeah, but for some reason IntelijIDEA decided that i need "^M" in some random lines. Better do another one without them.

**Comment by dragonjet** [comment]
let's try to merge, this repo has a JSON validator and will tell us if a build passes

**Comment by DynamicSTOP** [comment]
ok

**Comment by dragonjet** [comment]
seems build succeeded:
https://travis-ci.org/KC3Kai/kc3-translations/builds/146099466

**Pull request merged**
