### PR TITLE
[FR] Improved translation

### PR DESCRIPTION
**Pull request by Xwilarg**
About quest.json:
The word "Kanmasus" was used many times for "shipgirls", this word don't
mean anything in french, so I replaced it with the word "fille-navires",
who is a litteral translation.
Also changed "Chef" to "Navire Amirale".

About terms.json:
All lines of the english file are now translate into french, except :
- Some sentences between lines 130 and 140, because I don't know how to
translate them.
- Translations were reverse between lines 378 and 381, because the
sentences was too long to be displayable
https://i.gyazo.com/6d6d6d38217920491df7a4ce005ec19a.png

There are also 3 lines who are in the french file, but who aren't in the
english file... (Between lines 344 and 346)
"PredictionStampEscort" : "Escorte",
"PredictionStampMVPUseful" : "MVP",
"PredictionStampMVPUseless": "Déjà maximisé",

Without context, some sentences were hard to translate, and may not be
correct, depending of the context.

### CODE REVIEW

**Comment by dragonjet** [comment]
ah if it's not on the EN file, it's probably not used anymore, so you can remove them XD
I always forget when we have new translators that we have tools in this repo to help you.

If you can use python in your computer, you can use @Javran's `translation-diff.py`
or, I have made an online checker: http://kc3kai.github.io/kc3-translations/updater/

these will compare your language file with the EN one and show you what's missing or not yet translated

**Comment by dragonjet** [comment]
oh by the way, you have been invited to the org, and the translation team which will grant you direct write access to this repo

**Comment by rephira** [comment]
Kanmusu is the original Japanese portmanteau for the girls. For integrity purpose, we should first check what term other languages use with exception of Chinese as they would be using the original Chinese characters.

Korean uses Kanmusu fyi.

**Comment by Xwilarg** [comment]
dragonjet --> Thanks for the online checker :).
I began to learn Python, but it was a long time ago.

For the invitation, do I need to confirm it somewhere ?

**Comment by dragonjet** [comment]
yep, you may see an invitation from your email, or if not, see this page if there's anything

https://github.com/KC3Kai

**Pull request merged**
