### PR TITLE
[FR] Corrected some littles things on the french translation.

### PR DESCRIPTION
**Pull request by Xwilarg**
Shortened some lines because they were cut, also fixed some orthographic errors.

### CODE REVIEW

**Comment by nonsensed** [comment]
oops clicked something I shouldn't have, anyway thanks!

**Comment by Xwilarg** [comment]
Just a quick question, is it better that I create a new branch every time than using always the same ?

**Comment by mikenzb** [comment]
What I would recommended is that you fork the `KC3-translations` and you can make changes into your local master branch and then make a pull request to merge into the main `KC3kai/kc3-translations` branch.

You can find the fork button on the main page [here](https://github.com/KC3Kai/kc3-translations) and the fork button is in the top right, all you do after that is clone that forked repo into your PC and make changes to that and push there, when your ready you should be able to make a pull request to merge.

**Comment by Xwilarg** [comment]
Oki, thanks for your answer :).

**Pull request merged**
