### PR TITLE
[tcn]Update quotes.json

### PR DESCRIPTION
**Pull request by Rys3t**
I fix some of Shigure's Traditional Chinese subtitles because they don't work correctly.
Sorry for making mistakes on the last update.

### CODE REVIEW

**Comment by dragonjet** [comment]
got it, thanks again :+1:

**Comment by Rys3t** [comment]
Does it work right now or until the next version of kc3?
I don't understand.

**Comment by mikenzb** [comment]
It will be pushed to the next version of KC3, the translations only get updated every KC3 update.

**Comment by dragonjet** [comment]
it will be on webstore by the maintenance time

**Comment by Rys3t** [comment]
Thanks for explaining.
I got it.

**Pull request merged**
