### PR TITLE
Kr change

### PR DESCRIPTION
**Pull request by Reonasa**
npc added
Inazuma quotes fixed

### CODE REVIEW

**Comment by dragonjet** [comment]
@rephira @Yukinyaa

**Comment by rephira** [comment]
@Reonasa Hello. Would it be possible for you to join the KC3Kai gitter?

**Comment by Reonasa** [comment]
sure, why not. but I'm quite new to the github and how github works though, would be that ok?

**Comment by rephira** [comment]
No problem :) I am still getting used to it myself.

Here is the URL to the public gitter https://gitter.im/KC3Kai/Public.

**Pull request merged**
