### PR TITLE
[SCN] added Danyang vc translation

### PR DESCRIPTION
**Pull request by yang85**
Added some voice line translation for DanYang

### CODE REVIEW

**Comment by sinsinpub** [comment]
scn? i think u have misunderstood... `/tctn` not the Simplified Chinese folder, should be `/scn`. tctn might be the unused ver of `/tcn-yue`

**Comment by sinsinpub** [comment]
still didn't get me...? should edit the `/scn/quotes.json` file instead of `/tctn/quotes.json`.
u can see all the characters around ur modifications are 繁体字
image

**Comment by yang85** [comment]
for some reason my scn wasn't updated and the wrong one was loaded, fixing it rn

**Comment by yang85** [comment]
update, Thanks for double-checking

**Pull request closed without merging**
